publisher_scaled_joint_trajectory_controller:
  ros__parameters:

    controller_name: "scaled_joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]      ## TO MODIFY
    pos1:
      positions: [0.0, -1.198, -2.302, -1.221, 1.57, 2.763]     # HOME
    pos2:
      positions: [-1.506, -1.279, -1.598, -1.835, 1.566, 1.254]
    pos3:
      positions: [-1.472, -1.727, -2.147, -2.387, 4.705, 1.371]
    pos4:
      positions: [0.0, -1.671, -1.560, 0.107, 1.591, 1.361]
    # pos5:
    #   positions: [0.785, -1.57, 0.785, 0.785, 0.785, 0.785]

    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: true
    starting_point_limits:
      # shoulder_pan_joint: [-0.1,0.1]
      # shoulder_lift_joint: [-1.6,-1.5]
      # elbow_joint: [-0.1,0.1]
      # wrist_1_joint: [-1.6,-1.5]
      # wrist_2_joint: [-0.1,0.1]
      # wrist_3_joint: [-0.1,0.1]
      shoulder_pan_joint: [-0.1,0.1]
      shoulder_lift_joint: [-1.21,-1.19]
      elbow_joint: [-2.4,-2.2]
      wrist_1_joint: [-1.3,-1.1]
      wrist_2_joint: [1.5,1.6]
      wrist_3_joint: [2.7,2.9]

publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 6

    # goal_names: ["pos1", "pos2", "pos3", "pos4"]
    # pos1:
    #   positions: [0.785, -1.57, 0.785, 0.785, 0.785, 0.785]
    # pos2:
    #   positions: [0.0, -1.57, 0.0, 0.0, 0.0, 0.0]
    # pos3:
    #   positions: [0.0, -1.57, 0.0, 0.0, -0.785, 0.0]
    # pos4:
    #   positions: [0.0, -1.57, 0.0, 0.0, 0.0, 0.0]

    # joints:
    #   - shoulder_pan_joint
    #   - shoulder_lift_joint
    #   - elbow_joint
    #   - wrist_1_joint
    #   - wrist_2_joint
    #   - wrist_3_joint

    # check_starting_point: true
    # starting_point_limits:
    #   shoulder_pan_joint: [-0.1,0.1]
    #   shoulder_lift_joint: [-1.6,-1.5]
    #   elbow_joint: [-0.1,0.1]
    #   wrist_1_joint: [-1.6,-1.5]
    #   wrist_2_joint: [-0.1,0.1]
    #   wrist_3_joint: [-0.1,0.1]

    goal_names: ["pos1", "pos2", "pos3", "pos4"]      ## TO MODIFY
    pos1:
      positions: [0.0, -1.198, -2.302, -1.221, 1.57, 2.763]     # HOME
    pos2:
      positions: [-1.506, -1.279, -1.598, -1.835, 1.566, 1.254]
    pos3:
      positions: [-1.472, -1.727, -2.147, -2.387, 4.705, 1.371]
    pos4:
      positions: [0.0, -1.671, -1.560, 0.107, 1.591, 1.361]
    # pos5:
    #   positions: [0.785, -1.57, 0.785, 0.785, 0.785, 0.785]

    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: true
    starting_point_limits:
      # shoulder_pan_joint: [-0.1,0.1]
      # shoulder_lift_joint: [-1.6,-1.5]
      # elbow_joint: [-0.1,0.1]
      # wrist_1_joint: [-1.6,-1.5]
      # wrist_2_joint: [-0.1,0.1]
      # wrist_3_joint: [-0.1,0.1]
      shoulder_pan_joint: [-0.1,0.1]
      shoulder_lift_joint: [-1.21,-1.19]
      elbow_joint: [-2.4,-2.2]
      wrist_1_joint: [-1.3,-1.1]
      wrist_2_joint: [1.5,1.6]
      wrist_3_joint: [2.7,2.9]
